@istest
public class NumberToWord_Test {
    
    public static testMethod void testNumberToWord_nn(){
        
        NumberToWord.convert_nn(21);
        
        
        
    }
      public static testMethod void testNumberToWord_nn1(){
        
        NumberToWord.convert_nn(100);
        
        
        
    }
    
     public static testMethod void testNumberToWord_nn2(){
        
        NumberToWord.convert_nn(19);
        
        
        
    }
    
     public static testMethod void testNumberToWord_nnn(){
        
        NumberToWord.convert_nnn(1000);
          NumberToWord.convertWord(10000);
        
        
    }
    
    

}