/**
* Test class to provide coverage for ToolingAPIWSDLMetadata
**/

@isTest
private class Test_ToolingAPIWSDLMetadata {

    private static testMethod void TestToolingAPIWSDLMetadata()
    {

        new ToolingAPIWSDLMetadata.ProfileRecordTypeVisibility () ;
        new ToolingAPIWSDLMetadata.WorkflowFlowActionParameter () ;
        new ToolingAPIWSDLMetadata.Attachment () ;
        new ToolingAPIWSDLMetadata.Picklist () ;
        new ToolingAPIWSDLMetadata.WorkflowEmailRecipient () ;
        new ToolingAPIWSDLMetadata.ProfileApexPageAccess () ;
        new ToolingAPIWSDLMetadata.RecordTypePicklistValue () ;
        new ToolingAPIWSDLMetadata.Container () ;
        new ToolingAPIWSDLMetadata.FeedLayout () ;
        new ToolingAPIWSDLMetadata.RelatedContentItem () ;
        new ToolingAPIWSDLMetadata.ProfileExternalDataSourceAccess () ;
        new ToolingAPIWSDLMetadata.ComponentInstance () ;
        new ToolingAPIWSDLMetadata.MiniLayout () ;
        new ToolingAPIWSDLMetadata.WorkflowTimeTrigger () ;
        new ToolingAPIWSDLMetadata.SummaryLayoutItem () ;
        new ToolingAPIWSDLMetadata.QuickActionList () ;
        new ToolingAPIWSDLMetadata.FlexiPageRegion () ;
        new ToolingAPIWSDLMetadata.PrimaryTabComponents () ;
        new ToolingAPIWSDLMetadata.QuickActionListItem () ;
        new ToolingAPIWSDLMetadata.LayoutSection () ;
        new ToolingAPIWSDLMetadata.EscalationAction () ;
        new ToolingAPIWSDLMetadata.ProfileObjectPermissions () ;
        new ToolingAPIWSDLMetadata.ProfileApexClassAccess () ;
        new ToolingAPIWSDLMetadata.ProfileLoginIpRange () ;
        new ToolingAPIWSDLMetadata.SubtabComponents () ;
        new ToolingAPIWSDLMetadata.FeedLayoutFilter () ;
        new ToolingAPIWSDLMetadata.ComponentInstanceProperty () ;
        new ToolingAPIWSDLMetadata.ProfileFieldLevelSecurity () ;
        new ToolingAPIWSDLMetadata.ProfileCustomPermissions () ;
        new ToolingAPIWSDLMetadata.FeedLayoutComponent () ;
        new ToolingAPIWSDLMetadata.ProfileApplicationVisibility () ;
        new ToolingAPIWSDLMetadata.RelatedListItem () ;
        new ToolingAPIWSDLMetadata.SummaryLayout () ;
        new ToolingAPIWSDLMetadata.PackageVersion () ;
        new ToolingAPIWSDLMetadata.LayoutItem () ;
        new ToolingAPIWSDLMetadata.ProfileTabVisibility () ;
        new ToolingAPIWSDLMetadata.LookupFilter () ;
        new ToolingAPIWSDLMetadata.ProfileLoginHours () ;
        new ToolingAPIWSDLMetadata.SidebarComponent () ;
        new ToolingAPIWSDLMetadata.CustomConsoleComponents () ;
        new ToolingAPIWSDLMetadata.LayoutColumn () ;
        new ToolingAPIWSDLMetadata.ProfileUserPermission () ;
        new ToolingAPIWSDLMetadata.RelatedContent () ;
        new ToolingAPIWSDLMetadata.WorkflowActionReference () ;
        new ToolingAPIWSDLMetadata.FilterItem () ;
        new ToolingAPIWSDLMetadata.ReportChartComponentLayoutItem () ;
        new ToolingAPIWSDLMetadata.RelatedList () ;
        new ToolingAPIWSDLMetadata.RuleEntry () ;
        new ToolingAPIWSDLMetadata.FTestGeneratedEntityComplexValueType () ;
        new ToolingAPIWSDLMetadata.FTestGeneratedEntityComplexValueType2 () ;
        new ToolingAPIWSDLMetadata.AutoResponseRules () ;
        new ToolingAPIWSDLMetadata.FlexiPage () ;
        new ToolingAPIWSDLMetadata.CustomObject () ;
        new ToolingAPIWSDLMetadata.WorkflowFieldUpdate () ;
        new ToolingAPIWSDLMetadata.AssignmentRule () ;
        new ToolingAPIWSDLMetadata.PicklistValue () ;
        new ToolingAPIWSDLMetadata.Workflow () ;
        new ToolingAPIWSDLMetadata.WorkflowKnowledgePublish () ;
        new ToolingAPIWSDLMetadata.EscalationRule () ;
        new ToolingAPIWSDLMetadata.ValidationRule () ;
        new ToolingAPIWSDLMetadata.WorkflowOutboundMessage () ;
        new ToolingAPIWSDLMetadata.WorkflowAction () ;
        new ToolingAPIWSDLMetadata.WorkflowRule () ;
        new ToolingAPIWSDLMetadata.DataPipeline () ;
        new ToolingAPIWSDLMetadata.ApexClass () ;
        new ToolingAPIWSDLMetadata.WorkflowAlert () ;
        new ToolingAPIWSDLMetadata.EmailTemplate () ;
        new ToolingAPIWSDLMetadata.AssignmentRules () ;
        new ToolingAPIWSDLMetadata.CustomTab () ;
        new ToolingAPIWSDLMetadata.WorkflowSend () ;
        new ToolingAPIWSDLMetadata.WorkflowTask () ;
        new ToolingAPIWSDLMetadata.Profile () ;
        new ToolingAPIWSDLMetadata.WorkflowFlowAction () ;
        new ToolingAPIWSDLMetadata.RecordType () ;
        new ToolingAPIWSDLMetadata.ApexTrigger () ;
        new ToolingAPIWSDLMetadata.CompactLayout () ;
        new ToolingAPIWSDLMetadata.ApexPage () ;
        new ToolingAPIWSDLMetadata.EscalationRules () ;
        new ToolingAPIWSDLMetadata.Layout () ;
        new ToolingAPIWSDLMetadata.CustomField () ;
        new ToolingAPIWSDLMetadata.ApexComponent () ;
        new ToolingAPIWSDLMetadata.AutoResponseRule () ;    
    
    
    }
    
}