/*
Created By: Tarun Sharma
Created On: 01/10/2017
Purpose: Test Class for CARE Telemetry
Modified By:
*/
@isTest
public class Test_createCADiagnosticsService {
    
   private static testMethod void testCADiagnosticsSuccess(){
       /*  TestSLOMilestonesDataSetup.createTestDataforMilestones();
        Test_SetupData.createTestData();
        Case caseObj = [Select caseNumber from case where id=:Test_SetupData.caseNumberId limit 1];
        String jsonString = JSON.serialize('{"caseId":"'+caseObj.caseNumber+'","fileLocation":"www.alpha.com/cainc.remote.test.care-diagnostics-bucket/check","fileSize":"22KB","source":"Remote Enginner","status":"Open","uploadDate":"2017-01-04T14:04:53.000Z"}');
        Test.startTest();
        AWS_credentials__c  credentials = new AWS_credentials__c();
        credentials.Name = 'Care Telemetry';
        credentials.Key__c = 'AKIAJQRTMSNDKBKGAMGQ';
        credentials.Secret__c = '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';
        insert credentials;
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CreateDiagnostic';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(jsonString);
        RestContext.request = req;
        RestContext.response= res;
        createCADiagnosticsService.callCreateCADiagnostics(caseObj.caseNumber,'www.alpha.com/cainc.remote.test.care-diagnostics-bucket/check','22KB','Remote Enginner','Open','2017-01-04T14:04:53.000Z');
        //createCADiagnosticsService.callCreateCADiagnostics(Test_SetupData.caseNumberValue,'www.alpha.com','22KB','Remote Enginner','Open','2017-01-04T14:04:53.000Z');
        //createCADiagnosticsService.callCreateCADiagnostics('','www.alpha.com/cainc.remote.test.care-diagnostics-bucket/check','22KB','Remote Enginner','Open','2017-01-04T14:04:53.000Z');
        //createCADiagnosticsService.callCreateCADiagnostics('1','www.alpha.com/cainc.remote.test.care-diagnostics-bucket/check','22KB','Remote Enginner','Open','2017-01-04T14:04:53.000Z');
        test.stopTest();*/
    }
}