.digitalfootprint {
    display: flex; /* or inline-flex */
    flex-direction: row;
    flex-wrap: nowrap;
    font-family: sans-serif;
    max-width:1024px;
}

.digitalfootprint__left {
    flex-grow:4;
}

.digitalfootprint__middle {
    flex-grow:1;
    padding:5px 20px;
}

.digitalfootprint__right {
    flex-grow:1;
}

.digitalfootprint__overview {

    /*background:gray;*/
}

.digitalfootprint__overview .label {
    display: inline-block;
    padding:6px;
    color: white;
}