<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- saved from url=(0062)https://cs3.salesforce.com/resource/1292061980000/Help_For_OCV -->
<!-- saved from url=(0062)https://cs3.salesforce.com/resource/1289380274000/Help_For_OCV --><HTML><HEAD>
<META content="text/html; charset=utf-8" http-equiv=Content-Type>
<META name=GENERATOR content="MSHTML 8.00.7600.16671"><LINK rel=stylesheet 
type=text/css href="help.css"><LINK rel=stylesheet type=text/css 
href="Help_For_OCV_files/help.css"></HEAD>
<BODY>
<DIV id="Valuaton Rules" class=section><A name=Valuation_Rules><!-- --></A>
<H2 class=helpHead2><A name=heading_2_1><!-- --></A>Valuation Rules</H2>
<TABLE class=featureTable align=center>
  <TBODY>
  <TR>
    <TD class=labelCol><B>Price Inc. 9% (6% &amp; 3%):</B> <BR>Used to 
      increase pricing on a contract when both the 6% price increase, plus the 
      3% price increases listed below are applicable. </TD></TR>
  <TR>
    <TD><B>VSOE Stated Renewal:</B> <BR>Used when the original bookings had 
      revenue recognized upfront. </TD></TR>
  <TR>
    <TD><B>Price Inc. 6% :</B> <BR>Used to increase price on a contract 
      created before January 1, 2007 that is renewing for the first time (NOTE: 
      Worldwide price increase of 6% occurred) </TD></TR>
  <TR>
    <TD><B>Price Inc. 3% </B><BR>Used to increase price on a contract created 
      between January 2, 2007 and March 31, 2008 that is renewing for the first 
      time (NOTE: A GSA price increase took effect March 31, 2008 and a 
      Worldwide Price increase of 3% took effect April 1, 2008). If a contract 
      was created in April 2008, need to confirm the date that the quote was 
      created in order to verify whether 3% increase was already includesd, due 
      to the lapse of time when Sales creates the quote and Sales Accounting 
  </TD></TR>
  <TR>
    <TD><B>Contractual Cap:</B> <BR>Annual maintenance fee will not increase 
      more than a cert % annually. Any contract that has a CPI cap in the 
      agreement also goes under this valuation rule. </TD></TR>
  <TR>
    <TD><B>Stated Renewal:</B> <BR>Annual maintenance will be a specified 
      dollar amount </TD></TR>
  <TR>
    <TD><B>Stated Mnt Rate %:</B> <BR>Used if a contract states "a specific % 
      of the license list price is to be used to determine the renewal amount. 
      For example, "maintenance will be renewed at 15% of the prevailing license 
      list price". </TD></TR>
  <TR>
    <TD><B>Max Inc. ?:</B> <BR>Original deal was discounted and has no 
      contractual caps, stated renewals or stated maintenance rate %. Used even 
      if agreement states language such as "CA's then prevailing annual 
      maintenance fee (list maint), due to discounting". If deal is signed prior 
      to April 2008, the 3, 6, and 9% CA increase rule is chosen as long as it 
      is the first renewal. </TD></TR>
  <TR>
    <TD><B>List Price:</B> <BR>Contract is billing at current list for 
      maintenance. </TD></TR>
  <TR>
    <TD><B>Invalid:</B> <BR>Use for line items that are no longer valid and 
      invoicing (e.g. drop supported line items, license fee line, etc.). Rule 
      is also used for sellable (base line) line items. Not used for free of 
      charge products or any line item that will be renewaing even at $0 where 
      the customer is still going to be using the product. In these instances, 
      the same valuation rule used for other products on the contract shall 
      apply. </TD></TR>
  <TR>
    <TD><B>Education:</B> <BR>Education line items are not valued. Valuation 
      rule = education and invalid is placed in the comments field. Valuation 
      amount is zero. </TD></TR></TBODY></TABLE></DIV></BODY></HTML>
